package com.zhengshun.touch.api.domain;


import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table arc_sys_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class ArcSysUser implements Serializable{
    /**
     * Database Column Remarks:
     *   主键Id
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   姓名
     */
    private String name;

    /**
     * Database Column Remarks:
     *   账号
     */
    private String user_name;

    /**
     * Database Column Remarks:
     *   密码
     */
    private String password;

    /**
     * Database Column Remarks:
     *   工号
     */
    private String job_num;

    /**
     * Database Column Remarks:
     *   公司
     */
    private String company_id;

    /**
     * Database Column Remarks:
     *   部门
     */
    private String office_id;

    /**
     * Database Column Remarks:
     *   管辖机构
     */
    private String office_over;

    /**
     * Database Column Remarks:
     *   职位
     */
    private Integer position;

    /**
     * Database Column Remarks:
     *   邮箱
     */
    private String email;

    /**
     * Database Column Remarks:
     *   电话
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   手机
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   状态 0启用 1禁用
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   最近登录IP
     */
    private String login_ip;

    /**
     * Database Column Remarks:
     *   最近登录时间
     */
    private Date login_time;

    /**
     * Database Column Remarks:
     *   添加时间
     */
    private Date add_time;

    /**
     * Database Column Remarks:
     *   添加者
     */
    private String add_user;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    private Date update_time;

    /**
     * Database Column Remarks:
     *   修改者
     */
    private String update_user;

    /**
     * Database Column Remarks:
     *   备注
     */
    private String remark;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getJob_num() {
        return job_num;
    }

    public void setJob_num(String job_num) {
        this.job_num = job_num == null ? null : job_num.trim();
    }

    public String getCompany_id() {
        return company_id;
    }

    public void setCompany_id(String company_id) {
        this.company_id = company_id == null ? null : company_id.trim();
    }

    public String getOffice_id() {
        return office_id;
    }

    public void setOffice_id(String office_id) {
        this.office_id = office_id == null ? null : office_id.trim();
    }

    public String getOffice_over() {
        return office_over;
    }

    public void setOffice_over(String office_over) {
        this.office_over = office_over == null ? null : office_over.trim();
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public String getLogin_ip() {
        return login_ip;
    }

    public void setLogin_ip(String login_ip) {
        this.login_ip = login_ip == null ? null : login_ip.trim();
    }

    public Date getLogin_time() {
        return login_time;
    }

    public void setLogin_time(Date login_time) {
        this.login_time = login_time;
    }

    public Date getAdd_time() {
        return add_time;
    }

    public void setAdd_time(Date add_time) {
        this.add_time = add_time;
    }

    public String getAdd_user() {
        return add_user;
    }

    public void setAdd_user(String add_user) {
        this.add_user = add_user == null ? null : add_user.trim();
    }

    public Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    public String getUpdate_user() {
        return update_user;
    }

    public void setUpdate_user(String update_user) {
        this.update_user = update_user == null ? null : update_user.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}