package com.zhengshun.touch.api.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_user_game_data
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class TbUserGameData implements Serializable{
    private Long id;

    /**
     * Database Column Remarks:
     *   用户的微信头像 url
     */
    private String avatar_url;

    /**
     * Database Column Remarks:
     *   用户的微信昵称
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   用户的 openid
     */
    private String openid;

    /**
     * Database Column Remarks:
     *   用户kv数据
     */
    private String kv_data;

    /**
     * Database Column Remarks:
     *   用户状态 0 停用 1 正常
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   是否删除 0 否 1 是
     */
    private Integer delete_flag;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private Date create_date;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    private Date update_date;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAvatar_url() {
        return avatar_url;
    }

    public void setAvatar_url(String avatar_url) {
        this.avatar_url = avatar_url == null ? null : avatar_url.trim();
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    public String getKv_data() {
        return kv_data;
    }

    public void setKv_data(String kv_data) {
        this.kv_data = kv_data == null ? null : kv_data.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getDelete_flag() {
        return delete_flag;
    }

    public void setDelete_flag(Integer delete_flag) {
        this.delete_flag = delete_flag;
    }

    public Date getCreate_date() {
        return create_date;
    }

    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    public Date getUpdate_date() {
        return update_date;
    }

    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }
}